/*
 * generated by Xtext 2.21.0
 */
package org.ros.urdf.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import org.ros.model.urdf.RobotType
import org.ros.model.urdf.UrdfPackage

@ExtendWith(InjectionExtension)
@InjectWith(DslInjectorProvider)
class DslParsingTest {
	@Inject
	ParseHelper<RobotType> parseHelper
	
	@Test
	def void loadModel() {
			UrdfPackage.eINSTANCE.eClass();
		val result = parseHelper.parse('''
			robot test version="1.0" { }
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
