/*
 * generated by Xtext 2.21.0
 */
package org.ros.urdf.validation;


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class DslValidator extends AbstractDslValidator {
	

	
}
