/*
 * generated by Xtext 2.21.0
 */
package org.ros.urdf.formatting2

import com.google.inject.Inject
import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.ros.urdf.services.DslGrammarAccess
import org.eclipse.xtext.formatting2.IFormattableDocument

class DslFormatter extends AbstractFormatter2 {
	
	@Inject extension DslGrammarAccess
	
	override format(Object obj, IFormattableDocument document) {
		 
	}
	
 
}
