/*
 * generated by Xtext 2.21.0
 */
package org.ros.urdf.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.ros.model.urdf.UrdfPackage;
import org.ros.urdf.DslRuntimeModule;
import org.ros.urdf.DslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DslIdeSetup extends DslStandaloneSetup {

	@Override
	public Injector createInjector() {
		UrdfPackage.eINSTANCE.eClass();
		return Guice.createInjector(Modules2.mixin(new DslRuntimeModule(), new DslIdeModule()));
	}
	
}
