/*
 * generated by Xtext 2.21.0
 */
package org.ros.urdf;

import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.eclipse.xtext.resource.DerivedStateAwareResource;
import org.eclipse.xtext.resource.DerivedStateAwareResourceDescriptionManager;
import org.eclipse.xtext.resource.IDerivedStateComputer;
import org.eclipse.xtext.resource.IResourceDescription;
import org.eclipse.xtext.resource.XtextResource;
import org.ros.urdf.generator.UrdfStateComputer;
import org.ros.urdf.scoping.DslNameProvider;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class DslRuntimeModule extends AbstractDslRuntimeModule {

	public Class<? extends IDerivedStateComputer> bindIDerivedStateComputer() {
		return UrdfStateComputer.class;
	}

	@Override
	public Class<? extends XtextResource> bindXtextResource() {
		return DerivedStateAwareResource.class;
	}
	
	public Class<? extends IResourceDescription.Manager> bindIResourceDescriptionManager() {
		return DerivedStateAwareResourceDescriptionManager.class;
	}
		
	@Override
	public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {	
		return DslNameProvider.class;
	}
	
}
