/*
 * generated by Xtext 2.21.0
 */
package org.ros.urdf;

import org.ros.model.urdf.UrdfPackage;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class DslStandaloneSetup extends DslStandaloneSetupGenerated {

	public static void doSetup() {
		UrdfPackage.eINSTANCE.eClass();		
		new DslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
