/*
 * generated by Xtext 2.21.0
 */
package org.ros.urdf.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;
import org.ros.model.urdf.Joint;
import org.ros.model.urdf.Link;
import org.ros.model.urdf.MaterialGlobal;

import com.google.inject.Inject;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
public class DslLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public DslLabelProvider(final AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	String text(final Link link) {
		return "Link: "+ link.getName().toUpperCase();
	}
	
	String text(final MaterialGlobal material) {
		return "Material: "+material.getName().toUpperCase();
	}
	
	String text(final Joint joint) {
		return "Joint: "+joint.getName().toUpperCase();
	}
	
	
	// Labels and icons can be computed like this:
	
//	String text(Greeting ele) {
//		return "A greeting to " + ele.getName();
//	}
//
//	String image(Greeting ele) {
//		return "Greeting.gif";
//	}
}
